name: Build Windows executable

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==5.10.1 keyring yelpapi openai

      - name: Build Windows (call build script)
        run: |
          # By default the helper script builds a single-file executable. For debugging runtime/import issues
          # prefer using --OneDir by setting the OneDir switch below (comment/uncomment as needed).
          pwsh -File .\scripts\build_windows.ps1 -PythonExe python -OutDir dist

      - name: Show dist contents (for debugging upload path)
        run: |
          echo "Listing dist contents (if present)"
          if (Test-Path dist) { dir dist } else { echo "dist folder not present" }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-desktop-app
          path: dist/**
